name: Hearth
description: "Where emotions meet"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5

  # ðŸ“¦ State management
  provider: ^6.0.5

  # ðŸŽ§ Audio
  just_audio: ^0.9.34
  youtube_player_flutter: ^9.1.1

  # ðŸ”” Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  
  # ðŸŒ Env & HTTP
  flutter_dotenv: ^5.0.2
  http: ^0.13.6

  # ðŸ•“ Date formatting
  intl: ^0.18.0

  # ðŸŽ¨ Cupertino Icons
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/sounds/pop.mp3
    - .env
flutter_local_notifications:
  platform:
    linux:
      default_package: none
